CThreadImplLinux: fix build with uClibc
Fixes build error introduced by
https://github.com/xbmc/xbmc/commit/a5d17f691212e93d0a1eeadfd3b8fe19d1237fee

xbmc/platform/linux/threads/ThreadImplLinux.cpp:103:37: error:
  ‘gettid’ was not declared in this scope; did you mean ‘getgid’?
  103 |   : IThreadImpl(handle), m_threadID(gettid())