[wayland] fix compilation with C++17
Compilation for Wayland/gles fails with --std=c++17 because it has
stricter checks:

error: static assertion failed: comparison object must be invocable as const

Fix this error by declaring the result as const.

Fixes #15788

Signed-off-by: Olaf Hering <olaf@aepfle.de>