test/TestBasicEnvironment: include cores/DataCacheCore.h
Needed because gcc 4.8 complains about the use of std::unique_ptr<>
with a forward-declared type:

 /home/travis/build/xbmc/xbmc/xbmc/ServiceManager.h:47:7:   required from here
 /usr/include/c++/4.8/bits/unique_ptr.h:65:22: error: invalid application of ‘sizeof’ to incomplete type ‘CDataCacheCore’

Newer gcc versions do not have this problem, but unfortunately, the
Kodi build server runs this old version.