[xbmc] Add missing include <stdint.h>
Starting with gcc 15 it failed on musl libc with:

	/home/buildozer/git/aports/community/kodi/src/xbmc-21.2-Omega/xbmc/guilib/GUIMessage.h:378:15: error: unknown type name 'int64_t'
	  378 |               int64_t param1,
	      |               ^
	...