[cmake] Sync VideoSyncAndroid addition
VideoSyncAndroid.h:29: error: undefined reference to 'vtable for CVideoSyncAndroid'
ld: the vtable symbol may be undefined because the class is missing its key function
VideoReferenceClock.cpp:134: error: undefined reference to 'CVideoSyncAndroid::Setup(void (*)(int, unsigned long long))'
XBMCApp.cpp:847: error: undefined reference to 'CVideoSyncAndroid::FrameCallback(long long)'