SavestateFlatBuffer: Remove forward declararion of FlatBufferBuilder
This caused a compiler error with recent faltbuffers because the type changed:

In file included from xbmc/cores/RetroPlayer/savestates/SavestateDatabase.cpp:12:
xbmc/cores/RetroPlayer/savestates/SavestateFlatBuffer.h:19:7: error: definition of type 'FlatBufferBuilder' conflicts with type alias of the same name
class FlatBufferBuilder;
      ^
/usr/include/flatbuffers/flatbuffer_builder.h:1414:7: note: 'FlatBufferBuilder' declared here
using FlatBufferBuilder = FlatBufferBuilderImpl<false>;
      ^
1 error generated.

(cherry picked from commit 351184d7e4e3edc447d04a297769eb41a477ba68)