[tools/depends] bump pythonmodule-pil 7.1.2
Fix ios/tvos usage

rbpi requires to explicitly remove lcms, as it doesnt respect the --disable-lcms
flag for some reason, and causes a build failure trying to build the _imagingcms extension when it shouldnt
be building it at all.

 building 'PIL._imagingcms' extension
 /usr/bin/ccache /home/jenkins/rbpi-dev/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -fPIC -mcpu=cortex-a7 -mfloat-abi=hard -mfpu=neon-vfpv4 -mvectorize-with-neon-quad -pipe -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -Wno-deprecated-declarations -isystem/home/jenkins/rbpi-dev/firmware/opt/vc/include -isystem/home/jenkins/rbpi-dev/firmware/opt/vc/include/interface/vcos/pthreads -isystem/home/jenkins/rbpi-dev/firmware/opt/vc/include/interface/vmcs_host/linux -Og -g -D_DEBUG -isystem /home/jenkins/workspace/LINUX-RBPI/tools/depends/xbmc-depends/raspberry-pi2-debug/include -I/home/jenkins/workspace/LINUX-RBPI/tools/depends/xbmc-depends/raspberry-pi2-debug/include/freetype2 -I/home/jenkins/workspace/LINUX-RBPI/tools/depends/target/pythonmodule-pil/raspberry-pi2-debug/src/libImaging -I/home/jenkins/workspace/LINUX-RBPI/tools/depends/xbmc-depends/i686-linux-gnu-native/include -I/home/jenkins/workspace/LINUX-RBPI/tools/depends/xbmc-depends/raspberry-pi2-debug/include -I/home/jenkins/workspace/LINUX-RBPI/tools/depends/xbmc-depends/raspberry-pi2-debug/include/python3.7 -I/usr/local/include -I/usr/include -I/home/jenkins/workspace/LINUX-RBPI/tools/depends/xbmc-depends/i686-linux-gnu-native/include/python3.7 -c src/_imagingcms.c -o build/temp.linux-x86_64-3.7/src/_imagingcms.o
 In file included from /home/jenkins/workspace/LINUX-RBPI/tools/depends/xbmc-depends/raspberry-pi2-debug/include/python3.7/Python.h:11:0,
                 from src/_imagingcms.c:29:
 /usr/include/limits.h:26:36: fatal error: bits/libc-header-start.h: No such file or directory
   #include <bits/libc-header-start.h>
                                     ^
 compilation terminated.
 error: command '/usr/bin/ccache' failed with exit status 1
 Makefile:71: recipe for target '.installed-raspberry-pi2-debug' failed