[depends] pythonmodule-pil: Fold build_ext into --install-lib
A build error similar to what's described in
139909768b8cc49abcc10ab4f0d136ef1c0f5543 was observed when building for
Android, where webp and imagingcms shouldn't be built at all:

/usr/bin/ccache /home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -shared -L/home/dianlujitao/android-tools/xbmc-depends/aarch64-linux-android-21-debug/lib -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -L/home/dianlujitao/android-tools/xbmc-depends/aarch64-linux-android-21-debug/lib/android-21 -L/home/dianlujitao/android-tools/xbmc-depends/aarch64-linux-android-21-debug/lib/dummy-libkodi/ -lkodi -lm build/temp.linux-x86_64-3.7/src/_webp.o -L/home/dianlujitao/android-tools/xbmc-depends/x86_64-linux-gnu-native/lib -L/home/dianlujitao/android-tools/xbmc-depends/aarch64-linux-android-21-debug/lib -L/home/dianlujitao/android-tools/xbmc-depends/aarch64-linux-android-21-debug/lib/dummy-libkodi -L/usr/lib -L/opt/intel/compilers_and_libraries_2020.2.254/linux/compiler/lib/intel64_lin -L/opt/intel/mkl/lib/intel64 -L/usr/lib/libfakeroot -L/usr/local/lib -lwebp -lwebpmux -lwebpdemux -o build/lib.linux-x86_64-3.7/PIL/_webp.cpython-37-x86_64-linux-gnu.so
/usr/bin/ccache /home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -shared -L/home/dianlujitao/android-tools/xbmc-depends/aarch64-linux-android-21-debug/lib -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -L/home/dianlujitao/android-tools/xbmc-depends/aarch64-linux-android-21-debug/lib/android-21 -L/home/dianlujitao/android-tools/xbmc-depends/aarch64-linux-android-21-debug/lib/dummy-libkodi/ -lkodi -lm build/temp.linux-x86_64-3.7/src/_imagingcms.o -L/home/dianlujitao/android-tools/xbmc-depends/x86_64-linux-gnu-native/lib -L/home/dianlujitao/android-tools/xbmc-depends/aarch64-linux-android-21-debug/lib -L/home/dianlujitao/android-tools/xbmc-depends/aarch64-linux-android-21-debug/lib/dummy-libkodi -L/usr/lib -L/opt/intel/compilers_and_libraries_2020.2.254/linux/compiler/lib/intel64_lin -L/opt/intel/mkl/lib/intel64 -L/usr/lib/libfakeroot -L/usr/local/lib -llcms2 -o build/lib.linux-x86_64-3.7/PIL/_imagingcms.cpython-37-x86_64-linux-gnu.so
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible : skipping incompatible /usr/lib/libm.so/usr/lib/libm.so when searching for  when searching for -lm-lm

/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libm.a when searching for -lm
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libm.a when searching for -lm
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libwebp.so when searching for -lwebp
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/liblcms2.so when searching for -llcms2
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lwebp
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find : skipping incompatible -llcms2/usr/lib/libwebpmux.so
 when searching for -lwebpmux
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lwebpmux
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libwebpdemux.so when searching for -lwebpdemux
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lwebpdemux
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libdl.so when searching for -ldl
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libdl.a when searching for -ldl
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libdl.so when searching for -ldl
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libdl.a when searching for -ldl
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libc.a when searching for -lc
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libc.a when searching for -lc
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libdl.so when searching for -ldl
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libdl.a when searching for -ldl
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libdl.so when searching for -ldl
/home/dianlujitao/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: skipping incompatible /usr/lib/libdl.a when searching for -ldl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/ccache' failed with exit status 1
make[2]: *** [Makefile:57: .installed-aarch64-linux-android-21-debug] Error 1
make[2]: Leaving directory '/home/dianlujitao/xbmc/tools/depends/target/pythonmodule-pil'
make[1]: *** [Makefile:128: pythonmodule-pil] Error 2
make[1]: Leaving directory '/home/dianlujitao/xbmc/tools/depends/target'
make: *** [Makefile:11: target/.installed-aarch64-linux-android-21-debug] Error 2

The root cause is, for unknown reason, "setup.py install --install-lib"
invokes build_ext despise it's done before, but default settings this
time, which means --disable-foo are gone this time, and build errors
come. Do build_ext and install in a single command to fix the issue.

Co-authored-by: fuzzard <fuzzard@kodi.tv>