[cmake] Add missing dependencies to libcpluff
Some more missing add_dependencies(target libcpluff) lines were
missing. Fixes errors like the following when doing parallel build:

In file included from xbmc/addons/AddonManager.h:33:0,
                 from xbmc/ServiceManager.h:23,
                 from xbmc/Application.h:30,
                 from xbmc/windowing/X11/WinSystemX11GLContext.cpp:36
lib/cpluff/libcpluff/cpluff.h:44:23:
fatal error: cpluffdef.h: No such file or directory