[gui][fonts] store used fonts in std::unique_ptr
This secures the list management and in some circumstances avoids a mem leak if the list is emptied without delete in the entry.

The move to "GUIFontManager::GUIFontManager() = default;" was needed by this error on test:
```
In file included from /usr/include/c++/11/memory:76,
                 from /home/alwin/Development/Kodi/kodi-N/xbmc/utils/logtypes.h:11,
                 from /home/alwin/Development/Kodi/kodi-N/xbmc/settings/lib/ISettingControl.h:11,
                 from /home/alwin/Development/Kodi/kodi-N/xbmc/settings/SettingControl.h:11,
                 from /home/alwin/Development/Kodi/kodi-N/xbmc/settings/Settings.h:12,
                 from /home/alwin/Development/Kodi/kodi-N/xbmc/settings/Settings.cpp:9:
/usr/include/c++/11/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = CGUIFont]’:
/usr/include/c++/11/bits/unique_ptr.h:361:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = CGUIFont; _Dp = std::default_delete<CGUIFont>]’
/usr/include/c++/11/bits/stl_construct.h:140:22:   required from ‘constexpr void std::_Destroy(_Tp*) [with _Tp = std::unique_ptr<CGUIFont>]’
/usr/include/c++/11/bits/stl_construct.h:152:19:   required from ‘static void std::_Destroy_aux<<anonymous> >::__destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = std::unique_ptr<CGUIFont>*; bool <anonymous> = false]’
/usr/include/c++/11/bits/stl_construct.h:185:11:   required from ‘void std::_Destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = std::unique_ptr<CGUIFont>*]’
/usr/include/c++/11/bits/alloc_traits.h:746:15:   required from ‘void std::_Destroy(_ForwardIterator, _ForwardIterator, std::allocator<_T2>&) [with _ForwardIterator = std::unique_ptr<CGUIFont>*; _Tp = std::unique_ptr<CGUIFont>]’
/usr/include/c++/11/bits/stl_vector.h:680:15:   required from ‘std::vector<_Tp, _Alloc>::~vector() [with _Tp = std::unique_ptr<CGUIFont>; _Alloc = std::allocator<std::unique_ptr<CGUIFont> >]’
/home/alwin/Development/Kodi/kodi-N/xbmc/guilib/GUIFontManager.h:50:3:   required from ‘static std::shared_ptr<_Tp> xbmcutil::GlobalsSingleton<T>::getInstance() [with T = GUIFontManager]’
/home/alwin/Development/Kodi/kodi-N/xbmc/guilib/GUIFontManager.h:106:1:   required from here
/usr/include/c++/11/bits/unique_ptr.h:83:23: error: invalid application of ‘sizeof’ to incomplete type ‘CGUIFont’
   83 |         static_assert(sizeof(_Tp)>0,
      |                       ^~~~~~~~~~~
/usr/include/c++/11/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = CGUIFontTTF]’:
/usr/include/c++/11/bits/unique_ptr.h:361:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = CGUIFontTTF; _Dp = std::default_delete<CGUIFontTTF>]’
/usr/include/c++/11/bits/stl_construct.h:140:22:   required from ‘constexpr void std::_Destroy(_Tp*) [with _Tp = std::unique_ptr<CGUIFontTTF>]’
/usr/include/c++/11/bits/stl_construct.h:152:19:   required from ‘static void std::_Destroy_aux<<anonymous> >::__destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = std::unique_ptr<CGUIFontTTF>*; bool <anonymous> = false]’
/usr/include/c++/11/bits/stl_construct.h:185:11:   required from ‘void std::_Destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator = std::unique_ptr<CGUIFontTTF>*]’
/usr/include/c++/11/bits/alloc_traits.h:746:15:   required from ‘void std::_Destroy(_ForwardIterator, _ForwardIterator, std::allocator<_T2>&) [with _ForwardIterator = std::unique_ptr<CGUIFontTTF>*; _Tp = std::unique_ptr<CGUIFontTTF>]’
/usr/include/c++/11/bits/stl_vector.h:680:15:   required from ‘std::vector<_Tp, _Alloc>::~vector() [with _Tp = std::unique_ptr<CGUIFontTTF>; _Alloc = std::allocator<std::unique_ptr<CGUIFontTTF> >]’
/home/alwin/Development/Kodi/kodi-N/xbmc/guilib/GUIFontManager.h:50:3:   required from ‘static std::shared_ptr<_Tp> xbmcutil::GlobalsSingleton<T>::getInstance() [with T = GUIFontManager]’
/home/alwin/Development/Kodi/kodi-N/xbmc/guilib/GUIFontManager.h:106:1:   required from here
/usr/include/c++/11/bits/unique_ptr.h:83:23: error: invalid application of ‘sizeof’ to incomplete type ‘CGUIFontTTF’
```