[cmake] Fix compilation with msbuild (vs2015)
The CMake VS2015 generator sets the /Fd parameter (program database file
name) to <targetname>.pdb while the VS2014 generator used vc140.pdb.
Since we use precompiled headers over multiple static libraries we have to
use one single pdb file.

This fixes the errors:
fatal error C1083: Cannot open precompiled header file:
'C:/jenkins/slave/workspace/WIN-32/kodi-build/Release/objs/kodi.pch': No
such file or directory

See https://github.com/fetzerch/xbmc/commit/f626edf87a5af6c1f10d13d2d3b8103d6c2aadd1
for more information.