Revert "Revert "Merge pull request #18403 from lrusak/cpp17""
This reverts commit bd6818f1975ef4665d2319b482460f64aa4ae277.

This also includes a fix for the following:

    CLog: fix SPDLOG_LEVEL_NAMES to allow compiling

    Otherwise the following error occurs:

    xbmc/utils/log.h:12:89: error: ‘constexpr fmt::v8::basic_string_view<Char>::basic_string_view(const Char*) [with Char = char]’ called in a constant expression
       12 | #define SPDLOG_LEVEL_NAMES {"TRACE", "DEBUG", "INFO", "WARNING", "ERROR", "FATAL", "OFF"};
          |                                                                                         ^
    In file included from /usr/include/fmt/format.h:44,
                     from xbmc/utils/StringUtils.h:37,
                     from xbmc/utils/log.h:19,
    /usr/include/fmt/core.h:460:3: note: ‘constexpr fmt::v8::basic_string_view<Char>::basic_string_view(const Char*) [with Char = char]’ is not usable as a ‘constexpr’ function because:
      460 |   basic_string_view(const Char* s) : data_(s) {
          |   ^~~~~~~~~~~~~~~~~
    /usr/include/fmt/core.h:460:3: error: member ‘fmt::v8::basic_string_view<char>::size_’ must be initialized by mem-initializer in ‘constexpr’ constructor
    /usr/include/fmt/core.h:439:10: note: declared here
      439 |   size_t size_;
          |          ^~~~~