Scoped enum VideoContentType is not formattable
Introduces a template for the scoped enum VideoContentType to be formattable,
and fix the build with g++ 13.3.0 on Ubuntu 24.04 x86-64.

/usr/include/fmt/core.h:1757:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization