Fix compilation error due to missing include.
This fixes compilation error due to missing header.

 SDL_anigif.cpp: In function ‘int AG_LoadGIF_RW(SDL_RWops*, AG_Frame*, int)’:
 SDL_anigif.cpp:293:37: error: ‘malloc’ was not declared in this scope
   gd = (gifdata*)malloc( sizeof(*gd) );
                                     ^
 SDL_anigif.cpp:418:11: error: ‘free’ was not declared in this scope
   free( gd );
           ^
 make: *** [TexturePacker] Error 1