cmake: fix check for memfd_create
memfd_create is disabled on uClibc:
https://cgit.uclibc-ng.org/cgi/cgit/uclibc-ng.git/commit/?id=0bbc6a4bf54197ec5dab874750d125cbd5b9e877

Instead of checking for the header file we need to check for
memfd_create(), fixes build error

xbmc/utils/UDMABufferObject.cpp:94:13: error:
 ‘memfd_create’ was not declared in this scope

for this kodi config:

-DCORE_PLATFORM_NAME=wayland
-DWAYLAND_RENDER_SYSTEM=gl

-- Core system type: linux
-- Platform: wayland