Add missing cstddef includes
Fixes build errors seen with gcc 5.5.0:

xbmc/pictures/SlideShowPicture.cpp:903:109: error: 'offsetof' was not declared in this scope
   glVertexAttribPointer(posLoc, 3, GL_FLOAT, 0, sizeof(PackedVertex), BUFFER_OFFSET(offsetof(PackedVertex, x)));

xbmc/cores/RetroPlayer/rendering/VideoRenderers/RPRendererGuiTexture.cpp:187:109: error: 'offsetof' was not declared in this scope
   glVertexAttribPointer(posLoc, 3, GL_FLOAT, 0, sizeof(PackedVertex), BUFFER_OFFSET(offsetof(PackedVertex, x)));