[music] tagloadertaglib use defined unsigned int instead of uint + include header
Jenkins throws the following error when using taglib 2.0+ on MSVC platforms

\xbmc\music\tags\TagLoaderTagLib.cpp(607,7): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
(compiling source file '../xbmc/music/tags/TagLoaderTagLib.cpp')

Use unsigned int instead of either a typedef, or TagLib::uint.

Include tbytevector.h header explicitly to fix error.