[addons] change ADDON_GetTypeVersion to match windows build
Was required for windows to change function from
"const char* ADDON_GetTypeVersion(int type)" to
"void ADDON_GetTypeVersion(int type, const char** version)"
Windows have 'error C2059: Syntaxerror: "__declspec(dllexport)"' with them
before.