xbmc/addons: cppcheck performance fixes
```
xbmc/addons/AddonInstaller.cpp:629:53: performance: Searching before insertion is not necessary. Instead of 'result[pack]=std::make_unique<CFileItemList>()' consider using 'result.try_emplace(pack, std::make_unique<CFileItemList>());'. [stlFindInsert]
      result[pack] = std::make_unique<CFileItemList>();
                                                    ^
xbmc/addons/AddonVersion.cpp:178:13: performance: Ineffective call of function 'substr' because a prefix of the string is assigned to itself. Use resize() or pop_back() instead. [uselessCallsSubstr]
  version = version.substr(0, version.size() - 4);
            ^
xbmc/addons/ImageResource.cpp:23:3: performance: Variable 'm_type' is assigned in constructor body. Consider performing initialization in initialization list. [useInitializationList]
  m_type = Type(AddonType::RESOURCE_IMAGES)->GetValue("@type").asString();
  ^

xbmc/addons/LanguageResource.cpp:35:3: performance: Variable 'm_locale' is assigned in constructor body. Consider performing initialization in initialization list. [useInitializationList]
  m_locale =
  ^

xbmc/addons/addoninfo/AddonInfo.cpp:303:32: performance: Constructing a std::string_view from the result of c_str() is slow and redundant. [stlcstrConstructor]
        const std::string_view uid(filename.data() + startName.length());

xbmc/addons/addoninfo/AddonInfoBuilder.cpp:798:10: error: Uninitialized variable: libraryName [uninitvar]
  return libraryName;
         ^

```