epg/GUIEPGGridContainer: add missing CSingleLock in GetChannel(int)
Fixes random crashes when UpdateItems() runs while another thread
invokes CGUIWindowPVRGuide::UpdateSelectedItemPath() (via
CGUIWindowPVRBase::Notify() called by CEpgContainer::Notify()).
UpdateItems() invalidates m_channelItems and its items, while
GetChannel() dereferences one channel item.

This is how the crash looks like with gcc's AddressSanitizer:

ERROR: AddressSanitizer: heap-use-after-free on address 0x603001b025c8 at pc 0x000000e04b2a bp 0x7f8f8997abf0 sp 0x7f8f8997abe8
WRITE of size 4 at 0x603001b025c8 thread T19 (EPGUpdater)
    #0 0xe04b29 in __atomic_add /usr/include/c++/5/ext/atomicity.h:53
    #1 0xe04b29 in __atomic_add_dispatch /usr/include/c++/5/ext/atomicity.h:96
    #2 0xe04b29 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_add_ref_copy() /usr/include/c++/5/bits/shared_ptr_base.h:134
    #3 0xe04b29 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count(std::__shared_count<(__gnu_cxx::_Lock_policy)2> const&) /usr/include/c++/5/bits/shared_ptr_base.h:666
    #4 0xe04b29 in std::__shared_ptr<CFileItem, (__gnu_cxx::_Lock_policy)2>::__shared_ptr(std::__shared_ptr<CFileItem, (__gnu_cxx::_Lock_policy)2> const&) /usr/include/c++/5/bits/shared_ptr_base.h:923
    #5 0xe04b29 in std::shared_ptr<CFileItem>::shared_ptr(std::shared_ptr<CFileItem> const&) /usr/include/c++/5/bits/shared_ptr.h:107
    #6 0xe04b29 in EPG::CGUIEPGGridContainer::GetChannel(int) /home/max/git/kodi/xbmc/epg/GUIEPGGridContainer.cpp:1411
    #7 0x17d84c2 in PVR::CGUIWindowPVRGuide::UpdateSelectedItemPath() /home/max/git/kodi/xbmc/pvr/windows/GUIWindowPVRGuide.cpp:140
    #8 0x17c8f7d in PVR::CGUIWindowPVRBase::Notify(Observable const&, ObservableMessage) /home/max/git/kodi/xbmc/pvr/windows/GUIWindowPVRBase.cpp:90
    #9 0x16b3566 in Observable::SendMessage(Observable const&, ObservableMessage) /home/max/git/kodi/xbmc/utils/Observer.cpp:149
    #10 0x16b385e in Observable::NotifyObservers(ObservableMessage) /home/max/git/kodi/xbmc/utils/Observer.cpp:129
    #11 0xdf16d2 in EPG::CEpgContainer::Notify(Observable const&, ObservableMessage) /home/max/git/kodi/xbmc/epg/EpgContainer.cpp:212
    #12 0x16b3566 in Observable::SendMessage(Observable const&, ObservableMessage) /home/max/git/kodi/xbmc/utils/Observer.cpp:149
    #13 0x16b385e in Observable::NotifyObservers(ObservableMessage) /home/max/git/kodi/xbmc/utils/Observer.cpp:129
    #14 0xde370d in EPG::CEpg::UpdateEntries(EPG::CEpg const&, bool) /home/max/git/kodi/xbmc/epg/Epg.cpp:397
    #15 0xde38e5 in EPG::CEpg::LoadFromClients(long, long) /home/max/git/kodi/xbmc/epg/Epg.cpp:751
    #16 0xde4132 in EPG::CEpg::Update(long, long, int, bool) /home/max/git/kodi/xbmc/epg/Epg.cpp:464
    #17 0xdec052 in EPG::CEpgContainer::UpdateEPG(bool) /home/max/git/kodi/xbmc/epg/EpgContainer.cpp:665
    #18 0xdf05e5 in EPG::CEpgContainer::Process() /home/max/git/kodi/xbmc/epg/EpgContainer.cpp:364
    #19 0x1a7d05e in CThread::Action() /home/max/git/kodi/xbmc/threads/Thread.cpp:221
    #20 0x1a7d565 in CThread::staticThread(void*) /home/max/git/kodi/xbmc/threads/Thread.cpp:131
    #21 0x7f8fb2582283 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7283)
    #22 0x7f8faa78174c in clone (/lib/x86_64-linux-gnu/libc.so.6+0xe874c)