[tools/depends][native] Rustup 1.75.0
cargo-c fails to build on osx aarch64 host with the following failures

  error[E0658]: use of unstable library feature 'stdsimd'
     --> /Users/Shared/xbmc-depends/arm-darwin23.1.0-native/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.7/src/operations.rs:124:24
      |
  124 |     let res = unsafe { vaesmcq_u8(vaeseq_u8(transmute!(value), transmute!(0u128))) };
      |                        ^^^^^^^^^^
      |
      = note: see issue #48556 <https://github.com/rust-lang/rust/issues/48556> for more information

  error[E0658]: use of unstable library feature 'stdsimd'
     --> /Users/Shared/xbmc-depends/arm-darwin23.1.0-native/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.7/src/operations.rs:124:35
      |
  124 |     let res = unsafe { vaesmcq_u8(vaeseq_u8(transmute!(value), transmute!(0u128))) };
      |                                   ^^^^^^^^^
      |
      = note: see issue #48556 <https://github.com/rust-lang/rust/issues/48556> for more information

  error[E0658]: use of unstable library feature 'stdsimd'
     --> /Users/Shared/xbmc-depends/arm-darwin23.1.0-native/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.7/src/operations.rs:154:24
      |
  154 |     let res = unsafe { vaesimcq_u8(vaesdq_u8(transmute!(value), transmute!(0u128))) };
      |                        ^^^^^^^^^^^
      |
      = note: see issue #48556 <https://github.com/rust-lang/rust/issues/48556> for more information

  error[E0658]: use of unstable library feature 'stdsimd'
     --> /Users/Shared/xbmc-depends/arm-darwin23.1.0-native/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.7/src/operations.rs:154:36
      |
  154 |     let res = unsafe { vaesimcq_u8(vaesdq_u8(transmute!(value), transmute!(0u128))) };
      |                                    ^^^^^^^^^
      |
      = note: see issue #48556 <https://github.com/rust-lang/rust/issues/48556> for more information

     Compiling hkdf v0.12.4
  For more information about this error, try `rustc --explain E0658`.
  error: could not compile `ahash` (lib) due to 4 previous errors

Bump to 1.75.0 resolves this.