[depends] Fix undefined symbols on mdnsresponder
Introduced by https://github.com/xbmc/xbmc/pull/10025.

mDNSCore/mDNS.c:8688: error: undefined reference to 'FreeAnonInfo'
mDNSCore/mDNS.c:4386: error: undefined reference to 'FreeAnonInfo'
mDNSCore/mDNS.c:11945: error: undefined reference to 'FreeAnonInfo'
mDNSCore/mDNS.c:13157: error: undefined reference to 'FreeAnonInfo'
mDNSCore/mDNS.c:13137: error: undefined reference to 'AllocateAnonInfo'
mDNSCore/mDNS.c:13145: error: undefined reference to 'AllocateAnonInfo'
mDNSCore/mDNS.c:7271: error: undefined reference to 'InitializeAnonInfoForQuestion'
mDNSCore/mDNS.c:7318: error: undefined reference to 'SetAnonData'
mDNSCore/mDNS.c:9159: error: undefined reference to 'InitializeAnonInfoForCR'
mDNSCore/mDNS.c:8544: error: undefined reference to 'IdenticalAnonInfo'
mDNSCore/mDNS.c:9232: error: undefined reference to 'CopyAnonInfoForCR'
mDNSCore/mDNS.c:12069: error: undefined reference to 'AllocateAnonInfo'
mDNSCore/mDNS.c:12957: error: undefined reference to 'ReInitAnonInfo'
mDNSCore/mDNS.c:12970: error: undefined reference to 'ReInitAnonInfo'
mDNSCore/DNSCommon.c:1907: error: undefined reference to 'AnonInfoAnswersQuestion'
mDNSCore/DNSCommon.c:1941: error: undefined reference to 'AnonInfoAnswersQuestion'
mDNSCore/DNSCommon.c:1820: error: undefined reference to 'AnonInfoAnswersQuestion'