[filesystem] Switch to long for CURLPROXY_* enums
curl 8.16.0 bumped the enums to long, see: https://github.com/curl/curl/pull/18054

This fixes the build with curl 8.16+ for the following failure:

	/builds/alpine/aports/community/kodi/src/xbmc-21.2-Omega/xbmc/filesystem/CurlFile.cpp:48:5: error: cannot initialize an array element of type 'curl_proxytype' with an rvalue of type 'long'
	   48 |     CURLPROXY_HTTP,   CURLPROXY_SOCKS4,          CURLPROXY_SOCKS4A,
	      |     ^~~~~~~~~~~~~~
	/usr/include/curl/curl.h:791:35: note: expanded from macro 'CURLPROXY_HTTP'
	  791 | #define CURLPROXY_HTTP            0L /* added in 7.10, new in 7.19.4 default is
	      |                                   ^~
	...