xbmc/interfaces/python/swig.cpp: add missing initializer
After switching to python3.13 I see this issue:
| ../git/xbmc/interfaces/python/swig.cpp:78:5: error: missing initializer for member '_typeobject::tp_versions_used' [-Werror=missing-field-initializers]
|    78 |     };
|       |     ^
| cc1plus: some warnings being treated as errors

Add the missing initializer

Signed-off-by: Markus Volk <f_l_k@t-online.de>