[dbwrappers] Add missing include <cstdint>
Build fails with Kodi 22.0a1 on Alpine Linux edge (musl, gcc 15.2.0)
because it is missing the cstdint header for int64_t.

	In file included from /builds/alpine/aports/community/kodi/src/xbmc-22.0a1-Piers/xbmc/utils/DatabaseUtils.cpp:11:
	In file included from /builds/alpine/aports/community/kodi/src/xbmc-22.0a1-Piers/xbmc/dbwrappers/dataset.h:15:
	/builds/alpine/aports/community/kodi/src/xbmc-22.0a1-Piers/xbmc/dbwrappers/qry_dat.h:62:5: error: unknown type name 'int64_t'
	   62 |     int64_t int64_value;
	      |     ^
	/builds/alpine/aports/community/kodi/src/xbmc-22.0a1-Piers/xbmc/dbwrappers/qry_dat.h:79:30: error: unknown type name 'int64_t'
	   79 |   explicit field_value(const int64_t i);
	      |                              ^
	/builds/alpine/aports/community/kodi/src/xbmc-22.0a1-Piers/xbmc/dbwrappers/qry_dat.h:97:3: error: unknown type name 'int64_t'
	   97 |   int64_t get_asInt64() const;
	      |   ^
	/builds/alpine/aports/community/kodi/src/xbmc-22.0a1-Piers/xbmc/dbwrappers/qry_dat.h:149:32: error: unknown type name 'int64_t'
	  149 |   field_value& operator=(const int64_t i)
	      |                                ^
	/builds/alpine/aports/community/kodi/src/xbmc-22.0a1-Piers/xbmc/dbwrappers/qry_dat.h:234:26: error: unknown type name 'int64_t'
	  234 |   void set_asInt64(const int64_t i);
	      |                          ^
	5 errors generated.