[addons] fix help script "kodi-dev-kit/tools/code-generator/code_generator.py"
There was `find_loader` before used and where it is deprecated since Python 3.4 and since Python 3.12 removed, importlib.util.find_spec() about check and importlib.import_module() about import is used instead.
Further becomes with exception handling the load with importlib.import_module() checked and to prevent a crash risk on faults.

This fix it to have usable again.

Error message before:
```
$ ./code_generator.py
Traceback (most recent call last):
  File "/c/Dev/KODI/kodi/xbmc/addons/kodi-dev-kit/tools/code-generator/./code_generator.py", line 17, in <module>
    from src.commitChanges import *
  File "/c/Dev/KODI/kodi/xbmc/addons/kodi-dev-kit/tools/code-generator/src/commitChanges.py", line 18, in <module>
    git_found = importlib.find_loader("git") is not None
                ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'find_loader'
```