test/TestBasicEnvironment: add missing #include
Fixes compiler error:

 bits/unique_ptr.h:74:22: error: invalid application of 'sizeof' to incomplete type 'ANNOUNCEMENT::CAnnouncementManager'