[tvos] Fix some errors in copy scripts
DllPaths_generated.h only has .so libs, so change from dylib to match
We currently have no dylibs in $TARGET_FRAMEWORKS/"*dylib*, so just remove
this block. Fixes this message

error: /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /Users/Shared/jenkins/workspace/TVOS/build/build/Debug-appletvos/Kodi.app/Frameworks/*dylib* (No such file or directory)