[addons][filesystem] fix windows build about his RemoveDirectory macro
As there is a API function about "RemoveDirectory" becomes it in conflict with Windows if used.

This error then come:
```
error C2039: 'RemoveDirectoryW': is not a member of 'kodi::vfs'
```